apiVersion: v1
kind: Service
metadata:
  name: platform-operators-rukpak-core
  namespace: openshift-platform-operators-system
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: core
