apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: openshift-platform-operators/platform-operators-rukpak-webhook-certificate
    release.openshift.io/feature-gate: TechPreviewNoUpgrade
  name: platform-operators-rukpak-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: platform-operators-rukpak-webhook-service
      namespace: openshift-platform-operators
      path: /validate-core-rukpak-io-v1alpha1-bundle
  failurePolicy: Fail
  name: vbundles.core.rukpak.io
  rules:
  - apiGroups:
    - core.rukpak.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - bundles
  sideEffects: None
