apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    release.openshift.io/feature-gate: TechPreviewNoUpgrade
  name: platform-operators-rukpak-webhook-certificate
  namespace: openshift-platform-operators
spec:
  dnsNames:
  - platform-operators-rukpak-webhook-service.openshift-platform-operators.svc
  - platform-operators-rukpak-webhook-service.openshift-platform-operators.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: platform-operators-rukpak-selfsigned
  secretName: rukpak-webhook-certificate
