apiVersion: v1
kind: Service
metadata:
  name: platform-operators-rukpak-webhook-service
  namespace: openshift-platform-operators-system
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    app: webhooks
