apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: platform-operators-rukpak-core
  namespace: openshift-platform-operators-system
spec:
  dnsNames:
  - localhost
  - platform-operators-rukpak-core.openshift-platform-operators-system.svc
  - platform-operators-rukpak-core.openshift-platform-operators-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: rukpak-ca-issuer
  secretName: core-cert
