apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  annotations:
    release.openshift.io/feature-gate: TechPreviewNoUpgrade
  name: platform-operators-rukpak-ca-issuer
  namespace: openshift-platform-operators
spec:
  ca:
    secretName: rukpak-ca
